name: pluto detection test

on: workflow_dispatch

jobs:
  pluto_detect:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check deprecated k8s APIs
        uses: eddykaya/helm-pluto-github-action@0.0.2
        with:
          PLUTO_VERSION: 5.16.1
          K8S_VERSION: v1.24.8
          HELM_CHART_DIRECTORY: helm/charts/yahc
